DROP DATABASE IF EXISTS `calculoImc`;

CREATE DATABASE IF NOT EXISTS `calculoImc`;

USE `calculoImc`;

CREATE TABLE IF NOT EXISTS `User`  (
    `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `cpf` VARCHAR(11) NOT NULL,
    `telefone` VARCHAR(11) NOT NULL,
);

CREATE TABLE IF NOT EXISTS `Imc` (
    `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `height` DOUBLE NOT NULL,
    `weight` DOUBLE NOT NULL,
    `imc` DOUBLE NOT NULL,
    `date` DATETIME NOT NULL,
    `userId` INT,
    FOREIGN KEY(`userId`) REFERENCES `User`(`id`)   
);